package Principal;

public class ps2LinksReadme {

    static String texto = "Lista por alfabeto\n"
            + "Todos los juegos fueron probados con pcsx2 para checar su funcionamiento y unos pocos con ps2 con opl aniversario\n"
            + "#\n"
            + "http://q.gs/FRQTN\n"
            + "10.000 bullets\n"
            + "A\n"
            + "http://q.gs/FRQTO\n"
            + "Ace Combat Distant Thunder\n"
            + "http://q.gs/FRQTP\n"
            + "Ace Combat Squadron Leader\n"
            + "http://q.gs/FRQTQ\n"
            + "Ace Combat The Belkan War\n"
            + "http://q.gs/FRQTR\n"
            + "Adiboo and the Energy Thieve\n"
            + "http://q.gs/FRQTS\n"
            + "AeoFlux\n"
            + "http://q.gs/FRQTT\n"
            + "Agent Hugo\n"
            + "http://q.gs/FRQTU\n"
            + "Alias\n"
            + "http://q.gs/FRQTV\n"
            + "Alien Humanoid\n"
            + "http://q.gs/FRQTW\n"
            + "Aliens in the Attic\n"
            + "http://q.gs/FRQTX\n"
            + "Alone in the Dark-Nightmare\n"
            + "http://q.gs/FRQTY\n"
            + "Americas 10 Most Wanted\n"
            + "http://q.gs/FRQTZ\n"
            + "Amplitude\n"
            + "http://q.gs/FRQTa\n"
            + "Animaniacs - The Great Edgar\n"
            + "http://q.gs/FRQTb\n"
            + "Arc Twilight of the Spirits\n"
            + "http://q.gs/FRQTc\n"
            + "AREA 51\n"
            + "http://q.gs/FRQTd\n"
            + "Armored Core Nexus\n"
            + "http://q.gs/FRQTe\n"
            + "Army Men - Air Attack\n"
            + "http://q.gs/FRQTf\n"
            + "Army Men - Green Rogue\n"
            + "http://q.gs/FRQTg\n"
            + "Army Men - Sarges Heroes 2\n"
            + "http://q.gs/FRQTh\n"
            + "Artlist Collection - The Dog\n"
            + "http://q.gs/FRQTi\n"
            + "Auto Modellista\n"
            + "http://q.gs/FRQTj\n"
            + "Avatar The Legend of Aang\n"
            + "B\n"
            + "http://q.gs/FRQTk\n"
            + "Bakugan Battle Brawlers\n"
            + "http://q.gs/FRQTl\n"
            + "BATMAN BEGINS\n"
            + "http://q.gs/FRQTm\n"
            + "Batman - The Rise of Sin Tsu\n"
            + "http://q.gs/FRQTn\n"
            + "Batman -Vengance\n"
            + "http://q.gs/FRQTo\n"
            + "Batle engine\n"
            + "http://q.gs/FRQTp\n"
            + "Baldurs Gate - Dark Alliance\n"
            + "http://q.gs/FRQTq\n"
            + "Bard's Tale\n"
            + "http://q.gs/FRQTr\n"
            + "Beat Down Fists of Vengeance\n"
            + "http://q.gs/FRQTs\n"
            + "Ben 10 - Ultimate Alien\n"
            + "http://q.gs/FRQTt\n"
            + "Beverly Hills Cop\n"
            + "http://q.gs/FRQTu\n"
            + "Beyond Good and Evil\n"
            + "http://q.gs/FRQTv\n"
            + "Bionicle Heroes\n"
            + "http://q.gs/FRQTw\n"
            + "Bionicle\n"
            + "http://q.gs/FRQTx\n"
            + "BLACK\n"
            + "http://q.gs/FRQTy\n"
            + "Blood Will Tell - Osamus Tezuka\n"
            + "http://q.gs/FRQTz\n"
            + "BloodRayne\n"
            + "http://q.gs/FRQU0\n"
            + "BloodRayne 2\n"
            + "http://q.gs/FRQU1\n"
            + "Bloody Roar 4\n"
            + "http://q.gs/FRQU2\n"
            + "BMX XXX\n"
            + "http://q.gs/FRQU3\n"
            + "Breath of Fire Dragon Quarter\n"
            + "http://q.gs/FRQU4\n"
            + "Brothers in Arms - Earned in Blood\n"
            + "http://q.gs/FRQU5\n"
            + "Brothers in Arms - Road to Hill\n"
            + "http://q.gs/FRQU6\n"
            + "Buffy the Vampire Slayer Chao\n"
            + "http://q.gs/FRQU7\n"
            + "Bujingai Swordmaster\n"
            + "http://q.gs/FRQU8\n"
            + "Burnout Dominator\n"
            + "http://q.gs/FRQU9\n"
            + "Burnout 2 - Point of Impact\n"
            + "http://q.gs/FRQUA\n"
            + "Burnout 3 - Takedown \n"
            + "C\n"
            + "http://q.gs/FRQUB\n"
            + "Call of Duty - Finest Hour\n"
            + "http://q.gs/FRQUC\n"
            + "Call of Duty - World at War - Final Fronts\n"
            + "http://q.gs/FRQUD\n"
            + "Carmen Sandiego - The Secret of the Stolen Drums\n"
            + "http://q.gs/FRQUE\n"
            + "Cartoon Network Racing\n"
            + "http://q.gs/FRQUF\n"
            + "Castlevania\n"
            + "http://q.gs/FRQUG\n"
            + "Castlevania - Curse of Darkness\n"
            + "http://q.gs/FRQUH\n"
            + "Catwoman\n"
            + "http://q.gs/FRQUI\n"
            + "Champions - Return to Arms\n"
            + "http://q.gs/FRQUJ\n"
            + "CHAOS LEGION\n"
            + "http://q.gs/FRQUK\n"
            + "Charlie and the Chocolate\n"
            + "http://q.gs/FRQUL\n"
            + "Charlie's Angels\n"
            + "http://q.gs/FRQUM\n"
            + "Clock Tower 3\n"
            + "http://q.gs/FRQUN\n"
            + "Cold Fear\n"
            + "http://q.gs/FRQUO\n"
            + "Constantine\n"
            + "http://q.gs/FRQUP\n"
            + "Crash 'n' Burn\n"
            + "http://q.gs/FRQUQ\n"
            + "Crash Twinsanity\n"
            + "http://q.gs/FRQUR\n"
            + "Crisis Zone\n"
            + "http://q.gs/FRQUS\n"
            + "Crouching Tiger Hidden Dragon\n"
            + "http://q.gs/FRQUT\n"
            + "Crusty Demons \n"
            + "D\n"
            + "http://q.gs/FRQUU\n"
            + "DAKAR 2\n"
            + "http://q.gs/FRQUV\n"
            + "Dark Chronicle\n"
            + "http://q.gs/FRQUW\n"
            + "Death by Degrees\n"
            + "http://q.gs/FRQUX\n"
            + "Delta Force Black\n"
            + "http://q.gs/FRQUY\n"
            + "Destroy All Humans\n"
            + "http://q.gs/FRQUZ\n"
            + "Destroy All Humans 2\n"
            + "http://q.gs/FRQUa\n"
            + "Devil Kings\n"
            + "http://q.gs/FRQUb\n"
            + "Die Hard Vendetta\n"
            + "http://q.gs/FRQUc\n"
            + "Disaster Report \n"
            + "E\n"
            + "http://q.gs/FRQUd\n"
            + "Evil Twin Cypriens Chronicles \n"
            + "F \n"
            + "http://q.gs/FRQUe\n"
            + "Final Fantasy X \n"
            + "http://q.gs/FRQUf\n"
            + "Final Fantasy X-2 \n"
            + "http://q.gs/FRQUg\n"
            + "Final Fantasy XII\n"
            + "http://q.gs/FRQUh\n"
            + "Fireblade G\n"
            + "http://q.gs/FRQUi\n"
            + "Galerians: Ash \n"
            + "H \n"
            + "http://q.gs/FRQUj\n"
            + "Harvest Moon - A Wonderful Life\n"
            + "http://q.gs/FRQUk\n"
            + "Heroes of Might and Magic \n"
            + "http://q.gs/FRQUl\n"
            + "Hugo - Magic in the Trollwoods \n"
            + "I \n"
            + "http://q.gs/FRQUm\n"
            + "Ico \n"
            + "J \n"
            + "http://q.gs/FRQUn\n"
            + "Jackie Chan Adventures\n"
            + "http://q.gs/FRQUo\n"
            + "Jax Daxter \n"
            + "K \n"
            + "http://q.gs/FRQUp\n"
            + "Killzone \n"
            + "http://q.gs/FRQUq\n"
            + "kill.switch \n"
            + "http://q.gs/FRQUr\n"
            + "Kingdoom Hearts \n"
            + "http://q.gs/FRQUs\n"
            + "Kingdoom Hearts 2\n"
            + "http://q.gs/FRQUt\n"
            + "Kingdom Herart II final Mix \n"
            + "http://q.gs/FRQUu\n"
            + "KOF 2002 Unlimited Match\n"
            + "http://q.gs/FRQUv\n"
            + "Kuon\n"
            + "L\n"
            + "http://q.gs/FRQUw\n"
            + "La Fuga de Monkey Island\n"
            + "http://q.gs/FRQUx\n"
            + "LA Rush\n"
            + "http://q.gs/FRQUy\n"
            + "Lara Croft Tomb Raider - Anniversary\n"
            + "http://q.gs/FRQUz\n"
            + "Lara Croft Tomb Raider - Legend\n"
            + "http://q.gs/FRQV0\n"
            + "Lara Croft Tomb Raider - The Angel of Darkness\n"
            + "http://q.gs/FRQV1\n"
            + "Metal Gear Solid 3 - Subsistence\n"
            + "http://q.gs/FRQV2\n"
            + "Mouse Trophy\n"
            + "http://q.gs/FRQV3\n"
            + "Mr Bean\n"
            + "http://q.gs/FRQV4\n"
            + "Mummy Returns\n"
            + "N\n"
            + "http://q.gs/FRQV5\n"
            + "Namco Museum 50th Anniversary\n"
            + "http://q.gs/FRQV6\n"
            + "Ninja Assault\n"
            + "O\n"
            + "http://q.gs/FRQV7\n"
            + "Orphen - Scion of Sorcery\n"
            + "P\n"
            + "http://q.gs/FRQV8\n"
            + "Pac-Man World 2\n"
            + "Q\n"
            + "R\n"
            + "http://q.gs/FRQV9\n"
            + "Rayman - Raving Rabbids\n"
            + "http://q.gs/FRQVA\n"
            + "Riding Spirits\n"
            + "http://q.gs/FRQVB\n"
            + "Robin Hood - Defender of the Crown\n"
            + "http://q.gs/FRQVC\n"
            + "Rogue Galaxy\n"
            + "http://q.gs/FRQVD\n"
            + "Rumble Racing\n"
            + "http://q.gs/FRQVE\n"
            + "Rygar - The Legendary Adventure\n"
            + "S\n"
            + "http://q.gs/FRQVF\n"
            + "Saint Seiya - The Hades\n"
            + "http://q.gs/FRQVG\n"
            + "Saint Seiya - The Sanctuary\n"
            + "http://q.gs/FRQVH\n"
            + "Samurai Jack - The Shadow of Aku\n"
            + "http://q.gs/FRQVI\n"
            + "Samurai Western\n"
            + "http://q.gs/FRQVJ\n"
            + "School Days LxH\n"
            + "http://q.gs/FRQVK\n"
            + "Scooby-Doo! and the Spooky Swamp\n"
            + "http://q.gs/FRQVL\n"
            + "Scooby-Doo! First Frights\n"
            + "http://q.gs/FRQVM\n"
            + "Scooby-Doo! Unmasked\n"
            + "http://q.gs/FRQVN\n"
            + "Second Sight\n"
            + "http://q.gs/FRQVO\n"
            + "Secret Agent Clank\n"
            + "http://q.gs/FRQVP\n"
            + "Seek Destroy\n"
            + "http://q.gs/FRQVQ\n"
            + "Sega Ages 2500 Series GOLDEN AXE\n"
            + "http://q.gs/FRQVR\n"
            + "Sengoku Anthology\n"
            + "http://q.gs/FRQVS\n"
            + "Señor de los Anillos, El - Las Dos Torres\n"
            + "http://q.gs/FRQVT\n"
            + "Shadow Hearts From the New World\n"
            + "http://q.gs/FRQVU\n"
            + "Shadow Hearts II Covenant\n"
            + "http://q.gs/FRQVV\n"
            + "Shadow of the Colossus\n"
            + "http://q.gs/FRQVW\n"
            + "Shin Megami Tensei - Lucifer's Call\n"
            + "http://q.gs/FRQVX\n"
            + "Shin Megami Tensei - Persona 4\n"
            + "http://q.gs/FRQVY\n"
            + "Shinobi\n"
            + "http://q.gs/FRQVZ\n"
            + "Shinobido Way of the Ninja\n"
            + "http://q.gs/FRQVa\n"
            + "Silent Hill - Shattered Memories\n"
            + "http://q.gs/FRQVb\n"
            + "Silent Hill 2 - Directors Cut\n"
            + "http://q.gs/FRQVc\n"
            + "Silent Hill 2\n"
            + "http://q.gs/FRQVd\n"
            + "Silent Hill 3\n"
            + "http://q.gs/FRQVe\n"
            + "Silent Hill 4 - The Room\n"
            + "http://q.gs/FRQVf\n"
            + "Silent Hill Origins\n"
            + "http://q.gs/FRQVg\n"
            + "SOS - The Final Escape\n"
            + "http://q.gs/FRQVh\n"
            + "Space Chimps\n"
            + "http://q.gs/FRQVi\n"
            + "Spartan - Total Warrior\n"
            + "http://q.gs/FRQVj\n"
            + "Spider-Man - Friend or Foe\n"
            + "http://q.gs/FRQVk\n"
            + "Spider-Man - Web of Shadows - Amazing Allies Edition\n"
            + "http://q.gs/FRQVl\n"
            + "Spy Fiction\n"
            + "http://q.gs/FRQVm\n"
            + "SpyHunter - Nowhere to Run\n"
            + "http://q.gs/FRQVn\n"
            + "Spyro - A Heros Tale\n"
            + "http://q.gs/FRQVo\n"
            + "Star Wars Racer Revenge\n"
            + "http://q.gs/FRQVp\n"
            + "State of Emergency\n"
            + "http://q.gs/FRQVq\n"
            + "Steambot Chronicles\n"
            + "http://q.gs/FRQVr\n"
            + "Street Fighter Alpha Anthology\n"
            + "http://q.gs/FRQVs\n"
            + "Super Farm\n"
            + "http://q.gs/FRQVt\n"
            + "Swords of Destiny\n"
            + "http://q.gs/FRQVu\n"
            + "Syphon Filter - Dark Mirror\n"
            + "T\n"
            + "http://q.gs/FRQVv\n"
            + "The Lord of The Rings The Return of The\n"
            + "King\n"
            + "http://q.gs/FRQVw\n"
            + "The Lord Of The Rings The Third Age\n"
            + "http://q.gs/FRQVx\n"
            + "The Simpsons Hit Run\n"
            + "http://q.gs/FRQVy\n"
            + "The Sims\n"
            + "http://q.gs/FRQVz\n"
            + "The Sword of Etheria\n"
            + "http://q.gs/FRQW0\n"
            + "The Urbz Sims in the City\n"
            + "http://q.gs/FRQW1\n"
            + "Tim Burton's The Nightmare Before Christmas - Oogie's Revenge\n"
            + "http://q.gs/FRQW2\n"
            + "TMNT\n"
            + "http://q.gs/FRQW3\n"
            + "Tom and Jerry in War of the Whiskers\n"
            + "http://q.gs/FRQW4\n"
            + "Tom Clancy's Splinter Cell - Double Agent\n"
            + "http://q.gs/FRQW5\n"
            + "Tomb Raider - Underworld\n"
            + "http://q.gs/FRQW6\n"
            + "Torrente 3 - El Protector\n"
            + "http://q.gs/FRQW7\n"
            + "Total Overdose\n"
            + "http://q.gs/FRQW8\n"
            + "True Crime New York City\n"
            + "http://q.gs/FRQW9\n"
            + "Twisted Metal Black\n"
            + "U\n"
            + "http://q.gs/FRQWA\n"
            + "Urban Reign\n"
            + "V\n"
            + "http://q.gs/FRQWB\n"
            + "Vampire Night\n"
            + "http://q.gs/FRQWC\n"
            + "Virtua Cop - Elite Edition\n"
            + "W\n"
            + "http://q.gs/FRQWD\n"
            + "Wallace & Gromit - The Curse of the Were-Rabbit\n"
            + "http://q.gs/FRQWE\n"
            + "Walt Disney Pictures Presents Meet the Robinsons\n"
            + "http://q.gs/FRQWF\n"
            + "Warhammer 40,000 - Fire Warrior\n"
            + "http://q.gs/FRQWG\n"
            + "Whirl Tour\n"
            + "http://q.gs/FRQWH\n"
            + "Winx Club\n"
            + "http://q.gs/FRQWI\n"
            + "Without Warning\n"
            + "http://q.gs/FRQWJ\n"
            + "WWE SmackDown! Here Comes the Pain\n"
            + "Y\n"
            + "http://q.gs/FRQWK\n"
            + "Yu Yu Hakusho - Dark Tournament\n"
            + "http://q.gs/FRQWL\n"
            + "Yu-Gi-Oh! The Duelists of the Roses\n"
            + "X\n"
            + "http://q.gs/FRQWM\n"
            + "XGRA - Extreme G Racing Association\n"
            + "http://q.gs/FRQWN\n"
            + "Xiaolin Showdown\n"
            + "Z\n"
            + "http://q.gs/FRQWO\n"
            + "Zapper - One Wicked Cricket\n"
            + "http://q.gs/FRQWP\n"
            + "Zathura\n"
            + "http://q.gs/FRQWQ\n"
            + "Zone of the Enders - The 2nd Runner\n"
            + "http://q.gs/FRQWR\n"
            + "ZooCube";

    public static void main(String[] args) {
        String[] renglones = texto.split("\n");
        String link = "";
        String Etiqueta = "";
        for (String renglon : renglones) {
            if (renglon.startsWith("http")) {
                link = renglon;
                continue;
            }
            if (!link.isEmpty()) {
                System.out.println("## [" + renglon + "](" + link + ")");
                link = "";
            } else {
                System.out.println(renglon);
            }

        }
    }

}
